/* ═══════════════════════════════════════════════
   BROCE™ Investor Portal — Live Evidence Dashboard
   ═══════════════════════════════════════════════
   Fetches live data from /data/investor_evidence.json
   generated by core/drop_tower_pipeline.py
   ═══════════════════════════════════════════════ */

import { t } from '../i18n.js';
import { renderPageShell } from '../components/PageShell.js';
import { initScrollReveal } from '../utils/animations.js';

let evidenceData = null;

async function fetchEvidence() {
  try {
    const res = await fetch('/data/investor_evidence.json?t=' + Date.now());
    if (res.ok) evidenceData = await res.json();
  } catch (e) {
    console.warn('[Investor] Evidence data not available:', e.message);
  }
}

function renderLiveMetrics() {
  if (!evidenceData) {
    return `
      <div class="investor-metrics" data-stagger>
        <article class="investor-metric-card" data-tilt data-stagger-item>
          <p class="investor-metric-value" data-counter-target="2.6" data-counter-suffix="mm">2.6mm</p>
          <p class="investor-metric-label">${t('investor.metric1') || 'Gesamtdicke Apex System'}</p>
          <span class="investor-live"><span class="live-pulse"></span> Live</span>
        </article>
        <article class="investor-metric-card" data-tilt data-stagger-item>
          <p class="investor-metric-value" data-counter-target="3">3</p>
          <p class="investor-metric-label">${t('investor.metric3') || 'Patent-Anmeldungen'}</p>
          <span class="investor-live"><span class="live-pulse"></span> Live</span>
        </article>
        <article class="investor-metric-card" data-tilt data-stagger-item>
          <p class="investor-metric-value" data-counter-target="5">5</p>
          <p class="investor-metric-label">Schutzzonen</p>
          <span class="investor-live"><span class="live-pulse"></span> Live</span>
        </article>
        <article class="investor-metric-card" data-tilt data-stagger-item>
          <p class="investor-metric-value">Q2 '26</p>
          <p class="investor-metric-label">${t('investor.metric4') || 'Zertifizierung'}</p>
          <span class="investor-live"><span class="live-pulse"></span> Live</span>
        </article>
      </div>`;
  }

  const p = evidenceData.pipeline;
  const bestForce = p.best_force_kn < 999 ? p.best_force_kn.toFixed(1) : '—';
  const l2Status = p.level_2_achieved ? 'Level 2 ✅' : 'Pending';

  return `
    <div class="investor-metrics" data-stagger>
      <article class="investor-metric-card" data-tilt data-stagger-item>
        <p class="investor-metric-value investor-metric-highlight">${bestForce}<span class="metric-unit">kN</span></p>
        <p class="investor-metric-label">Best Measured Force</p>
        <span class="investor-live"><span class="live-pulse"></span> Live from Pipeline</span>
      </article>
      <article class="investor-metric-card" data-tilt data-stagger-item>
        <p class="investor-metric-value">${p.total_tests}</p>
        <p class="investor-metric-label">Drop-Tower Tests</p>
        <span class="investor-live"><span class="live-pulse"></span> Live</span>
      </article>
      <article class="investor-metric-card" data-tilt data-stagger-item>
        <p class="investor-metric-value">${l2Status}</p>
        <p class="investor-metric-label">EN 1621-1 @ ${p.level_2_thickness_mm}mm</p>
        <span class="investor-live"><span class="live-pulse"></span> Live</span>
      </article>
      <article class="investor-metric-card" data-tilt data-stagger-item>
        <p class="investor-metric-value">±${p.mean_prediction_error_pct}%</p>
        <p class="investor-metric-label">Simulator Accuracy</p>
        <span class="investor-live"><span class="live-pulse"></span> Live</span>
      </article>
    </div>`;
}

function renderDropTestTable() {
  if (!evidenceData || !evidenceData.tests || evidenceData.tests.length === 0) {
    return `<p class="evidence-empty">Keine Test-Daten verfügbar. Pipeline wurde noch nicht ausgeführt.</p>`;
  }

  const rows = evidenceData.tests.map(test => {
    const l2 = test.level_2_pass;
    const l1 = test.level_1_pass;
    const badge = l2 ? '<span class="evidence-badge verified">L2 ✅</span>'
      : l1 ? '<span class="evidence-badge pending">L1 ⚠️</span>'
        : '<span class="evidence-badge failed">FAIL ❌</span>';
    const errClass = Math.abs(test.prediction_error_pct) < 15 ? 'good' : 'warn';

    return `
      <tr class="test-row ${l2 ? 'test-pass' : ''}">
        <td class="td-zone">${test.zone}</td>
        <td>${test.config_name}</td>
        <td class="td-force ${l2 ? 'force-pass' : ''}">${test.measured_force_kn.toFixed(1)}</td>
        <td>${test.peak_force_kn.toFixed(1)}</td>
        <td class="td-predicted">${test.predicted_force_kn.toFixed(1)}</td>
        <td class="td-error ${errClass}">${test.prediction_error_pct > 0 ? '+' : ''}${test.prediction_error_pct.toFixed(1)}%</td>
        <td>${badge}</td>
      </tr>`;
  }).join('');

  return `
    <div class="test-table-wrap">
      <table class="test-table">
        <thead>
          <tr>
            <th>Zone</th>
            <th>Config</th>
            <th>Measured</th>
            <th>Peak</th>
            <th>Predicted</th>
            <th>Error</th>
            <th>Result</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
}

function renderZoneBest() {
  if (!evidenceData || !evidenceData.zone_best || Object.keys(evidenceData.zone_best).length === 0) {
    return '';
  }

  const zones = Object.entries(evidenceData.zone_best).map(([zone, data]) => {
    const pct = Math.max(0, Math.min(100, (1 - data.force_kn / 35) * 100));
    const l2 = data.level_2;
    return `
      <div class="zone-result-card ${l2 ? 'zone-pass' : ''}">
        <div class="zone-header">
          <h4>${zone}</h4>
          ${l2 ? '<span class="evidence-badge verified">Level 2</span>' : '<span class="evidence-badge pending">In Progress</span>'}
        </div>
        <div class="zone-force">${data.force_kn.toFixed(1)} <span class="metric-unit">kN</span></div>
        <div class="zone-bar-wrap">
          <div class="zone-bar" style="width:${pct}%"></div>
          <div class="zone-threshold" style="left:${((1 - 20 / 35) * 100)}%"></div>
        </div>
        <div class="zone-bar-labels">
          <span>35 kN (L1)</span>
          <span class="zone-l2-label">20 kN (L2)</span>
          <span>0 kN</span>
        </div>
        <p class="zone-meta">${data.config} · ${data.date}</p>
      </div>`;
  }).join('');

  return `<div class="zone-results-grid">${zones}</div>`;
}

function renderPatentStatus() {
  if (!evidenceData || !evidenceData.patent_status) return '';

  const patents = Object.entries(evidenceData.patent_status).map(([id, p]) => {
    const statusClass = p.status === 'filed' ? 'verified'
      : p.status === 'ready_to_file' ? 'pending'
        : 'future';
    const statusLabel = p.status === 'filed' ? 'Eingereicht'
      : p.status === 'ready_to_file' ? 'Bereit'
        : p.status;
    return `
      <div class="patent-card">
        <div class="patent-id">${id}</div>
        <div class="patent-title">${p.title}</div>
        <div class="patent-mapping">${p.mapping}</div>
        <span class="evidence-badge ${statusClass}">${statusLabel}</span>
      </div>`;
  }).join('');

  return `<div class="patent-grid">${patents}</div>`;
}

function renderMilestones() {
  if (!evidenceData || !evidenceData.milestones) return '';

  return evidenceData.milestones.map(m => {
    const icon = m.status === 'complete' ? '✓' : m.status === 'pending' ? '○' : '◆';
    const state = m.status === 'complete' ? 'done' : m.status === 'pending' ? 'future' : 'current';
    const date = m.date ? `<span class="ms-date">${m.date}</span>` : '';
    return `
      <article class="milestone-card ms-${state}">
        <span class="ms-icon">${icon}</span>
        <h4>${m.name}</h4>
        ${date}
      </article>`;
  }).join('');
}

export async function renderInvestorPage(container) {
  // Fetch live evidence data
  await fetchEvidence();

  const hasLiveData = evidenceData !== null;
  const lastUpdate = hasLiveData
    ? new Date(evidenceData.generated_at).toLocaleString('de-DE')
    : null;

  const content = `
    <section class="section page-hero-section" id="top">
      <div class="container" style="text-align:center; max-width:820px;">
        <p class="eyebrow" data-reveal="up">${t('investor.hero.eyebrow') || 'INVESTOR INTELLIGENCE'}</p>
        <h1 data-reveal="up" data-decode>${t('investor.hero.title') || 'Live Evidence Dashboard'}</h1>
        <p class="lead" data-reveal="up">${t('investor.hero.subtitle') || 'Echtzeitdaten aus dem BROCE Intelligence System'}</p>
        ${lastUpdate ? `<p class="dashboard-timestamp">Letztes Update: ${lastUpdate}</p>` : ''}
      </div>
    </section>

    <!-- Live Metrics from Pipeline -->
    <section class="section section-tight" style="padding-top:0;">
      <div class="container">
        ${renderLiveMetrics()}
      </div>
    </section>

    <!-- Zone Performance Dashboard -->
    ${hasLiveData && Object.keys(evidenceData.zone_best || {}).length > 0 ? `
    <section class="section">
      <div class="container">
        <div class="section-head" data-reveal="up">
          <p class="eyebrow">DROP-TOWER RESULTS</p>
          <h2>Zone Performance</h2>
        </div>
        ${renderZoneBest()}
      </div>
    </section>` : ''}

    <!-- Drop-Tower Test Log -->
    ${hasLiveData ? `
    <section class="section section-muted">
      <div class="container">
        <div class="section-head" data-reveal="up">
          <p class="eyebrow">TEST PROTOCOL</p>
          <h2>EN 1621-1 Drop-Tower Log</h2>
          <p class="section-subtitle">${evidenceData.pipeline.total_tests} Tests · Best: ${evidenceData.pipeline.best_force_kn.toFixed(1)} kN · ${evidenceData.pipeline.total_calibrations} Calibrations</p>
        </div>
        ${renderDropTestTable()}
      </div>
    </section>` : ''}

    <!-- Patent Status -->
    <section class="section">
      <div class="container">
        <div class="section-head" data-reveal="up">
          <p class="eyebrow">INTELLECTUAL PROPERTY</p>
          <h2>Patent Portfolio</h2>
        </div>
        ${hasLiveData ? renderPatentStatus() : `
          <div class="patent-grid">
            <div class="patent-card">
              <div class="patent-id">DPMA_001</div>
              <div class="patent-title">STF-Infiltrated TPMS</div>
              <div class="patent-mapping">PAT-004</div>
              <span class="evidence-badge pending">Bereit</span>
            </div>
            <div class="patent-card">
              <div class="patent-id">DPMA_002</div>
              <div class="patent-title">Integriertes Garment System</div>
              <div class="patent-mapping">PAT-006</div>
              <span class="evidence-badge pending">Bereit</span>
            </div>
            <div class="patent-card">
              <div class="patent-id">DPMA_003</div>
              <div class="patent-title">Körperadaptive Gradierung</div>
              <div class="patent-mapping">PAT-005</div>
              <span class="evidence-badge pending">Bereit</span>
            </div>
          </div>`
    }
      </div>
    </section>

    <!-- Milestones -->
    <section class="section section-muted">
      <div class="container">
        <div class="section-head" data-reveal="up">
          <p class="eyebrow">${t('investor.progress.eyebrow') || 'ROADMAP'}</p>
          <h2>${t('investor.progress.title') || 'Milestones'}</h2>
        </div>
        <div class="milestones-grid">
          ${hasLiveData ? renderMilestones() : `
            ${[
        { icon: '✓', title: t('investor.ms1.title') || 'Gold Standard STLs', desc: t('investor.ms1.desc') || '5 zones validated', state: 'done' },
        { icon: '✓', title: t('investor.ms2.title') || 'Patent Drafts', desc: t('investor.ms2.desc') || '3 DPMA ready', state: 'done' },
        { icon: '◆', title: t('investor.ms3.title') || 'Physical Validation', desc: t('investor.ms3.desc') || 'Drop-tower testing', state: 'current' },
        { icon: '○', title: t('investor.ms4.title') || 'CE Certification', desc: t('investor.ms4.desc') || 'EN 1621-1 Level 2', state: 'future' }
      ].map(m => `
              <article class="milestone-card ms-${m.state}">
                <span class="ms-icon">${m.icon}</span>
                <h4>${m.title}</h4>
                <p>${m.desc}</p>
              </article>
            `).join('')}
          `}
        </div>
      </div>
    </section>

    <!-- Portal Cards -->
    <section class="section">
      <div class="container">
        <div class="section-head" data-reveal="up">
          <p class="eyebrow">${t('investor.portal.eyebrow') || 'DATA ROOM'}</p>
          <h2>${t('investor.portal.title') || 'Documentation'}</h2>
        </div>
        <div class="investor-portal-grid" data-stagger>
          <article class="investor-portal-card" data-tilt data-stagger-item>
            <div class="portal-card-icon">
              <svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="2" stroke="currentColor" stroke-width="1.5" fill="none"/><line x1="9" y1="9" x2="15" y2="9" stroke="currentColor" stroke-width="1.5"/><line x1="9" y1="13" x2="15" y2="13" stroke="currentColor" stroke-width="1.5"/></svg>
            </div>
            <h3>${t('investor.card1.title') || 'Technical Documentation'}</h3>
            <p>${t('investor.card1.text') || 'EN 1621-1 test protocol, material specifications, manufacturing process.'}</p>
          </article>
          <article class="investor-portal-card" data-tilt data-stagger-item>
            <div class="portal-card-icon">
              <svg viewBox="0 0 24 24"><path d="M12 20V10" stroke="currentColor" stroke-width="1.5"/><path d="M18 20V4" stroke="currentColor" stroke-width="1.5"/><path d="M6 20v-4" stroke="currentColor" stroke-width="1.5"/></svg>
            </div>
            <h3>${t('investor.card2.title') || 'Financial Projections'}</h3>
            <p>${t('investor.card2.text') || 'Unit economics, 5-year model, comparable exits (Koroyd €40-65M).'}</p>
          </article>
          <article class="investor-portal-card" data-tilt data-stagger-item>
            <div class="portal-card-icon">
              <svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>
            </div>
            <h3>${t('investor.card3.title') || 'IP Portfolio'}</h3>
            <p>${t('investor.card3.text') || '3 DPMA patents (PAT-004 to PAT-006), evidence-linked claims.'}</p>
          </article>
          <article class="investor-portal-card" data-tilt data-stagger-item>
            <div class="portal-card-icon">
              <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="1.5" fill="none"/><path d="M2 12h20" stroke="currentColor" stroke-width="1.5"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>
            </div>
            <h3>${t('investor.card4.title') || 'Market Analysis'}</h3>
            <p>${t('investor.card4.text') || 'TAM €13.2B, SAM €1.39B EU premium segment.'}</p>
          </article>
        </div>
      </div>
    </section>

    <!-- CTA -->
    <section class="section">
      <div class="container">
        <div class="cta-panel" data-reveal="up">
          <p class="eyebrow">${t('investor.cta.eyebrow') || 'NEXT STEP'}</p>
          <h2>${t('investor.cta.title') || 'Due Diligence starten'}</h2>
          <p>${t('investor.cta.text') || 'Alle Daten in diesem Dashboard sind live und verifizierbar.'}</p>
          <div class="cta-actions">
            <a href="mailto:invest@broce.eu" class="btn btn-primary">${t('investor.cta.btn1') || 'Contact'}</a>
            <a href="mailto:hello@broce.eu" class="btn btn-secondary">${t('investor.cta.btn2') || 'Learn More'}</a>
          </div>
        </div>
      </div>
    </section>
  `;

  renderPageShell(container, { title: t('page.investor') || 'Investor', content });
}
